/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package picoyplaca;

import java.util.Date;

/**
 *
 * @author ASUS
 */


public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
        setLocationRelativeTo(this); // muestra el programa en el centro de la pantalla
        this.Label_error1.setVisible(false); //Al inicio no son visibles los mensajes de placa incorrecta
        this.Label_error2.setVisible(false);
        Date now = new Date();
        this.Calendario.setDate(now);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_titulo = new javax.swing.JLabel();
        Label_informacionplaca = new javax.swing.JLabel();
        Label_error1 = new javax.swing.JLabel();
        TextField_placa = new javax.swing.JTextField();
        Label_error2 = new javax.swing.JLabel();
        Label_informacioncalendario = new javax.swing.JLabel();
        Calendario = new com.toedter.calendar.JDateChooser();
        Label_informacionhorario = new javax.swing.JLabel();
        ComboBox_horarios = new javax.swing.JComboBox<>();
        Boton_verificacion = new javax.swing.JButton();
        Label_resultados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_titulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Label_titulo.setForeground(new java.awt.Color(204, 0, 255));
        Label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_titulo.setText("SISTEMA DE VALIDACIÓN DE PICO Y PLACA");

        Label_informacionplaca.setText("Ingrese el número de placa. Ejemplo PBD3212");

        Label_error1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_error1.setForeground(new java.awt.Color(255, 0, 0));
        Label_error1.setText("El numero de placa es incorrecto !!!");

        Label_error2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_error2.setForeground(new java.awt.Color(255, 0, 0));
        Label_error2.setText("*");

        Label_informacioncalendario.setText("Eliga una fecha");

        Label_informacionhorario.setText("Elija un horario");

        ComboBox_horarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00h00-06h59", "07h00-09h30", "09h31-15h59", "16h00-19h30", "19h31-23h59" }));

        Boton_verificacion.setBackground(new java.awt.Color(255, 204, 0));
        Boton_verificacion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Boton_verificacion.setForeground(new java.awt.Color(102, 102, 102));
        Boton_verificacion.setText("VERIFICAR");
        Boton_verificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_verificacionActionPerformed(evt);
            }
        });

        Label_resultados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_error2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label_informacioncalendario))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_informacionhorario)
                                            .addComponent(ComboBox_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Label_informacionplaca))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 48, Short.MAX_VALUE)
                                .addComponent(Label_titulo)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_error1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(Boton_verificacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Label_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_informacionplaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_error1)
                            .addComponent(Label_error2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_informacionhorario)
                            .addComponent(Label_informacioncalendario, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboBox_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Boton_verificacion)
                .addGap(18, 18, 18)
                .addComponent(Label_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_verificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_verificacionActionPerformed
        // TODO add your handling code here:
    SistemaPicoYPlaca sistema = new SistemaPicoYPlaca();
    sistema.validacionPlaca(this.TextField_placa, this.Label_error1, this.Label_error2);
    sistema.verificacionDeRestriccion(this.Calendario, this.ComboBox_horarios, this.TextField_placa, this.Label_resultados, this.Label_error1, this.Label_error2);
  
    }//GEN-LAST:event_Boton_verificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_verificacion;
    private com.toedter.calendar.JDateChooser Calendario;
    private javax.swing.JComboBox<String> ComboBox_horarios;
    private javax.swing.JLabel Label_error1;
    private javax.swing.JLabel Label_error2;
    private javax.swing.JLabel Label_informacioncalendario;
    private javax.swing.JLabel Label_informacionhorario;
    private javax.swing.JLabel Label_informacionplaca;
    private javax.swing.JLabel Label_resultados;
    private javax.swing.JLabel Label_titulo;
    private javax.swing.JTextField TextField_placa;
    // End of variables declaration//GEN-END:variables
}
